#!/usr/bin/env node
/**
 * Build the browser half into the artifact the Harness client loader consumes.
 *
 * The loader does not import a plain ES module; it calls
 * `window.__ModuleLoader__.load({ id, factory })` and reads `module.exports` from
 * the factory. Official client plugins produce that shape with `tsdown` plus a
 * battery of plugins (CSS Modules, sourcemap chaining, a bundle-purity gate that
 * permits only declared module-table imports).
 *
 * This plugin's browser half imports nothing at all — it reads the DOM and calls
 * one RPC — so none of that machinery applies. Wrapping the compiled ES module is
 * the whole build:
 *
 * - no bare specifier means no `require(...)`, so there is nothing for the loader
 *   module table to answer and nothing the purity gate could reject;
 * - no CSS means no stylesheet pipeline;
 * - `dsh.client.inject` still names the client packages whose services this half
 *   uses, which is what establishes load order.
 *
 * Usage: node scripts/build-client.mjs   (run after `tsc`)
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const SOURCE = join(ROOT, 'lib', 'client', 'index.js')
const OUTPUT = join(ROOT, 'lib', 'client.js')

/** Package name, used as the loader id and in diagnostics. */
const PACKAGE_NAME = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).name

/** A bare specifier would need a module-table row; this half must have none. */
const BARE_IMPORT = /(?:^|[\s;{(])import\s*\(?\s*['"]([^'"]+)['"]|(?:^|[\s;{(])require\(\s*['"]([^'"]+)['"]/gu

/**
 * Verify the compiled module is self-contained.
 *
 * The loader would throw at runtime on a specifier its table cannot answer, and
 * the failure would surface as a broken plugin rather than a build error, so this
 * is checked here instead.
 *
 * @param code - the compiled ES module.
 * @throws {Error} when a bare import or require remains.
 */
function assertSelfContained(code) {
  for (const match of code.matchAll(BARE_IMPORT)) {
    const specifier = match[1] ?? match[2]
    if (specifier === undefined || specifier.startsWith('.') || specifier.startsWith('node:')) continue
    throw new Error(
      `client bundle: compiled code imports the bare specifier ${JSON.stringify(specifier)}. `
      + 'The browser half must be self-contained (or declare it in dsh.client.external).',
    )
  }
}

/** Build the loader artifact. */
function main() {
  let source
  try {
    source = readFileSync(SOURCE, 'utf8')
  } catch (error) {
    console.error(`client bundle: ${SOURCE} is missing; run the TypeScript build first`)
    throw error
  }
  assertSelfContained(source)

  // The compiled module is ESM; the loader expects a factory returning the module
  // namespace. TypeScript emits inline `export const` / `export function` for a
  // module like this one, so the keyword is stripped and the names are collected
  // into a trailing return.
  const exported = []
  const body = source
    .replace(/^\/\/# sourceMappingURL=.*$/mu, '')
    .replace(/^export\s+(?:declare\s+)?(const|let|var|function|class|async\s+function)\s+([A-Za-z_$][\w$]*)/gmu,
      (_whole, kind, name) => {
        exported.push(name)
        return `${kind} ${name}`
      })
    .replace(/^export\s*\{([^}]*)\};?\s*$/gmu, (_whole, names) => {
      for (const entry of names.split(',')) {
        const name = entry.trim().split(/\s+as\s+/u).pop()
        if (name !== undefined && name !== '') exported.push(name)
      }
      return ''
    })

  if (exported.length === 0) {
    throw new Error('client bundle: the compiled module exports nothing to hand to the loader')
  }
  const stripped = `${body}\nreturn { ${[...new Set(exported)].join(', ')} };\n`

  const artifact = [
    '/* Generated by scripts/build-client.mjs — do not edit. */',
    `window.__ModuleLoader__.load({ id: ${JSON.stringify(PACKAGE_NAME)}, factory: (require) => {`,
    'var module = { exports: {} }; var exports = module.exports;',
    stripped,
    'return module.exports; } });',
    '',
  ].join('\n')

  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, artifact)
  console.log(`client bundle: wrote ${OUTPUT} (${Buffer.byteLength(artifact)} bytes)`)
}

main()
